// THIS FILE IS AUTOMATICALLY GENERATED IN:
//
//   build-utils/update-index-file.js
//
// YOU SHOULD NEVER UPDATE THIS FILE DIRECTLY
import AnimatedLine from './components/AnimatedLine.vue'
import Button from './components/Button.vue'
import ButtonGroup from './components/ButtonGroup.vue'
import Calendar from './components/Calendar.vue'
import CheckBox from './components/CheckBox.vue'
import DateInput from './components/DateInput.vue'
import DateTimeInput from './components/DateTimeInput.vue'
import Loading from './components/Loading.vue'
import SelectInput from './components/SelectInput.vue'
import StatusLabel from './components/StatusLabel.vue'
import TextInput from './components/TextInput.vue'
// Export components individually
export { AnimatedLine, Button, ButtonGroup, Calendar, CheckBox, DateInput, DateTimeInput, Loading, SelectInput, StatusLabel, TextInput }
// What should happen if the user installs the library as a plugin
function install(Vue) {
  Vue.component('AnimatedLine', AnimatedLine)
  Vue.component('Button', Button)
  Vue.component('ButtonGroup', ButtonGroup)
  Vue.component('Calendar', Calendar)
  Vue.component('CheckBox', CheckBox)
  Vue.component('DateInput', DateInput)
  Vue.component('DateTimeInput', DateTimeInput)
  Vue.component('Loading', Loading)
  Vue.component('SelectInput', SelectInput)
  Vue.component('StatusLabel', StatusLabel)
  Vue.component('TextInput', TextInput)
}
// Export the library as a plugin
export default { install: install }
